services:
  - type: web
    name: workshop-fotografia-protesta
    runtime: static
    staticPublishPath: .
    headers:
      - path: /img/*
        name: Cache-Control
        value: public, max-age=604800
